name: Continuous Deployment

on:
  push:
    branches:
      - main  # Sesuaikan dengan branch yang Anda gunakan

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          rsync -avz --delete-after ./ vianziro@103.109.210.53:/path/to/deploy/
